### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by yanqiangmiffy** [lich99/ChatGLM-finetune-LoRA#16]
运行`accelerate launch --config_file config/default_config.yaml train_new.py`,然后报错：

```
Traceback (most recent call last):
  File "/home/searchgpt/yq/ChatGLM-finetune-LoRA/train_new.py", line 38, in <module>
    accelerator = Accelerator(mixed_precision=mixed_precision, gradient_accumulation_steps=accumulate_step, deepspeed_plugin=deepspeed_plugin)
  File "/home/searchgpt/anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/accelerate/accelerator.py", line 340, in __init__
    self.state = AcceleratorState(
  File "/home/searchgpt/anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/accelerate/state.py", line 539, in __init__
    PartialState(cpu, **kwargs)
  File "/home/searchgpt/anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/accelerate/state.py", line 123, in __init__
    torch.cuda.set_device(self.device)
  File "/home/searchgpt/anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

运行环境为：单机2卡A100

**Comment by yanqiangmiffy** [comment]
显卡数量为2，config.yaml文件里面需要将process设置为2
